module.exports = {
  Menu: require("./menu"),
  Comment: require("./comment"),
  LikeVideo: require("./likeVideo"),
  MenuVideo: require("./menuVideo"),
  Metadata: require("./metadata"),
  Video: require("./video"),
  Users: require("./users"),
  AdminUsers: require("./adminUsers"),
  ProductVideo: require("./productVideo"),
  Product: require("./product"),
  Review: require("./review"),
  CommentThumb: require('./commentThumb'),
  LiveSessions: require('./liveSessions'),
  ProductMenus: require('./productMenus'),
  ProductMenuEntity: require('./productMenuEntity'),
  Pages: require('./pages'),
}